### ISSUE TITLE
Escape file names in NativeProcess

### ISSUE THREAD

**Issue by mitkus** [lightbend/reactive-cli#109]
File names are now passed as-is to stdlib.system, this might lead to unexpected issues.

@longshorej:
> I think we should technically be escaping the stdinFile and outputFile. In our immediate case we're fine since we're only passing in temp files, but if the method was used for something else that contained spaces it would break.

**Comment by TimMoore** [comment]
Lightbend Orchestration is no longer actively developed and will reach its [End of Life](https://developer.lightbend.com/docs/lightbend-platform/2.0/support-terminology/index.html#end-of-life-eol-) on April 15, 2020.

We recommend [Migrating to the Improved Kubernetes Deployment Experience](https://developer.lightbend.com/docs/lightbend-orchestration/current/migration.html).
