### ISSUE TITLE
Enable setting of restartPolicy for Jobs

### ISSUE THREAD

**Issue by dsugden** [lightbend/reactive-cli#114]
https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#restart-policy

add flag to override default restartPolicy of OnFailure for Jobs.

**Comment by longshorej** [comment]
@mitkus could you look at this one? We need a `--pod-controller-restart-policy` that when provided overrides the generated restartPolicy for Deployment and Job types.

Note this relevant type exists in the code already:

```scala
  object RestartPolicy extends Enumeration {
    val Never, OnFailure, Always = Value
  }
```
