### ISSUE TITLE
HTTP parsing should use proper parser

### ISSUE THREAD

**Issue by fsat** [lightbend/reactive-cli#12]
For example parsing [query string](https://github.com/typesafehub/reactive-cli/pull/8/files#diff-21c69d89a2e2d6faf52fecfd5190e960R135) or [WWW Auth Header](https://github.com/typesafehub/reactive-cli/pull/8/files#diff-21c69d89a2e2d6faf52fecfd5190e960R140) should be done using a proper parser instead.

**Comment by fsat** [comment]
I'd recommend `fastparse` as it's quite reasonable to use and it has Scala Native binaries published.

**Comment by longshorej** [comment]
Closed via #99

**Comment by fsat** [comment]
Thanks @mitkus and @longshorej !
