### ISSUE TITLE
Get ReadyCheckUrl and HealthCheckUrl from docker image labels

### ISSUE THREAD

**Issue by mitkus** [lightbend/reactive-cli#134]
Also need to add this label in sbt/maven plugins.

**Comment by alanngai** [comment]
may be related to lightbend/platform-team#51?

**Comment by TimMoore** [comment]
Lightbend Orchestration is no longer actively developed and will reach its [End of Life](https://developer.lightbend.com/docs/lightbend-platform/2.0/support-terminology/index.html#end-of-life-eol-) on April 15, 2020.

We recommend [Migrating to the Improved Kubernetes Deployment Experience](https://developer.lightbend.com/docs/lightbend-orchestration/current/migration.html).
