### ISSUE TITLE
Ubuntu 18.04 apt support

### ISSUE THREAD

**Issue by idoshamun** [lightbend/reactive-cli#144]
Currently the bintray repository doesn't support the Bionic Beaver LTS version.
Would you mind supporting this version?

**Comment by longshorej** [comment]
I presume this can be done by simply updating this `BuildInfo`:

https://github.com/lightbend/reactive-cli/blob/master/project/BuildInfo.scala#L87-L98

**Comment by mitkus** [comment]
Ubuntu Bionic now builds fine, but I cannot upload the package to Bintray:

```
[info] PublishDeb dist=bionic, component=main, arch=amd64
[info] Uploading reactive-cli_1.2.0-bionic_amd64.deb to https://api.bintray.com/content/lightbend/deb/reactive-cli/1.2.0/reactive-cli_1.2.0-bionic_amd64.deb
[trace] Stack trace suppressed: run last root/compile:publishToBintray for the full output.
[error] (root/compile:publishToBintray) [400 Bad Request] {"message":"Unable to upload files: Could not extract metadata for artifact 'reactive-cli_1.2.0-bionic_amd64.deb', content might be malformed."}
```

Maybe Bintray doesn't recognise `bionic` distribution name yet?

**Comment by dwijnand** [comment]
Tried to see if Bintray now support Ubuntu Bionic but, after enabling ubuntu-18-04 and disabling every other target, running `compile:publishToBintray` I get:

```
Status: Downloaded newer image for lightbend-docker-registry.bintray.io/rp/reactive-cli-build-ubuntu-18-04:latest
docker: Error response from daemon: OCI runtime create failed: container_linux.go:348: starting container process caused "exec: \"./command\": stat ./command: no such file or directory": unknown.
time="2018-08-14T16:35:57+01:00" level=error msg="error waiting for container: context canceled"
[debug] Forcing garbage collection...
[trace] Stack trace suppressed: run last root/compile:buildAll for the full output.
[error] (root/compile:buildAll) java.lang.AssertionError: assertion failed: Executing WrappedArray(docker, run, --rm=true, --env, BINTRAY_USER=none, --env, BINTRAY_PASS=none, -v, /d/reactive-cli/target/stage/ubuntu-18-04:/root/stage, -v, /d/reactive-cli/target/.ivy2/cache:/root/.ivy2/cache, -v, /d/reactive-cli/target/.sbt/launchers:/root/.sbt/launchers, lightbend-docker-registry.bintray.io/rp/reactive-cli-build-ubuntu-18-04:latest) yielded 127, expected 0
[error] Total time: 239 s, completed 14-Aug-2018 16:35:58
```

**Comment by dwijnand** [comment]
Could be relevant:

* https://unix.stackexchange.com/a/446263/37284
* https://github.com/sbt/sbt-native-packager/issues/1067

**Comment by longshorej** [comment]
Depending upon the libs that 18.04 ships with, you might be able to do the build using 17.04, similar to how the 17.10 build is done. To do this, you'd add `bionic` here: https://github.com/lightbend/reactive-cli/blob/master/project/BuildInfo.scala#L98

`sbt "build ubuntu-17-04_17-10"` will create debs that can then be tested on an 18.04 VM.

**Comment by dwijnand** [comment]
Same result:

```
> build ubuntu-17-04_17-10
[info] [ubuntu-17-04_17-10] building
[info] [ubuntu-17-04_17-10] copying project
latest: Pulling from rp/reactive-cli-build-ubuntu-17-04_17-10
8b23367590c3: Pulling fs layer
d18b5715fdd4: Pulling fs layer
5ba295b2a11b: Pulling fs layer
31ace8c1d433: Pulling fs layer
95434b428ba1: Pulling fs layer
26046d65c450: Pulling fs layer
8640e7d96a66: Pulling fs layer
31ace8c1d433: Waiting
95434b428ba1: Waiting
26046d65c450: Waiting
8640e7d96a66: Waiting
5ba295b2a11b: Download complete
d18b5715fdd4: Verifying Checksum
d18b5715fdd4: Download complete
95434b428ba1: Verifying Checksum
95434b428ba1: Download complete
31ace8c1d433: Verifying Checksum
31ace8c1d433: Download complete
8640e7d96a66: Verifying Checksum
8640e7d96a66: Download complete
8b23367590c3: Verifying Checksum
8b23367590c3: Download complete
8b23367590c3: Pull complete
d18b5715fdd4: Pull complete
5ba295b2a11b: Pull complete
31ace8c1d433: Pull complete
95434b428ba1: Pull complete
26046d65c450: Verifying Checksum
26046d65c450: Download complete
26046d65c450: Pull complete
8640e7d96a66: Pull complete
Digest: sha256:cb4d2b5466b4cc694da7b03cb2db4d4dfaa4745995933ddd7708593ad1f3802e
Status: Downloaded newer image for lightbend-docker-registry.bintray.io/rp/reactive-cli-build-ubuntu-17-04_17-10:latest
docker: Error response from daemon: OCI runtime create failed: container_linux.go:348: starting container process caused "exec: \"./command\": stat ./command: no such file or directory": unknown.
[trace] Stack trace suppressed: run last root/compile:build for the full output.
[error] (root/compile:build) java.lang.AssertionError: assertion failed: Executing WrappedArray(docker, run, --rm=true, --env, BINTRAY_USER=none, --env, BINTRAY_PASS=none, -v, /d/reactive-cli/target/stage/ubuntu-17-04_17-10:/root/stage, -v, /d/reactive-cli/target/.ivy2/cache:/root/.ivy2/cache, -v, /d/reactive-cli/target/.sbt/launchers:/root/.sbt/launchers, lightbend-docker-registry.bintray.io/rp/reactive-cli-build-ubuntu-17-04_17-10:latest) yielded 127, expected 0
[error] Total time: 220 s, completed 14-Aug-2018 17:33:46
```

**Comment by longshorej** [comment]
Hrm :confused:, it's working for me on:

```
~/work/lightbend/reactive-cli#master $ uname -a
Linux meddle 4.17.5-1-ARCH #1 SMP PREEMPT Sun Jul 8 17:27:31 UTC 2018 x86_64 GNU/Linux
-> 0

~/work/lightbend/reactive-cli#master $ docker --version
Docker version 18.05.0-ce, build f150324782
-> 0
```

I've observed some strangeness with Docker builds after kernel upgrades, requiring a reboot. If you're doing the Linux builds from a Mac or Windows (i.e. Docker running in a VM), I'm not sure that I've ever tested that.

**Comment by longshorej** [comment]
I attempted to build for bionic using the 17.04 build image but libre2-3 and libcurl3 ended up being problematic. Maybe a ticket should be opened up with Bintray?

**Comment by longshorej** [comment]
Alternatively, could modify the build to use the musl build for all Linux distros, subject to the normal static/dynamically linked debate. Note that this build is already used for RHEL6 and older Debian derivatives.

**Comment by dwijnand** [comment]
@longshorej Sounds fine to me. But I'll let @eed3si9n decide.

**Comment by eed3si9n** [comment]
Sounds like a good workaround in the short-term at least.
In the long-term, I would add this situation as a reference point to the maintenance burden of shipping native app specific to a Linux distribution.

**Comment by kwehden** [comment]
libre2 has has several security issues, and has been removed from 18.04 + most likely because of that. Not sure this a version issue.

**Comment by longshorej** [comment]
AFAIK, the 18.04 build works but fails to upload to Bintray due to package format issues -- something changed in 18.04 wrt how it builds .deb packages. I don't recall the details though.

**Comment by dwijnand** [comment]
Yes I agree, I think it's https://github.com/lightbend/reactive-cli/issues/144#issuecomment-412917171.

**Comment by TimMoore** [comment]
https://github.com/sbt/sbt-native-packager/issues/1067 has some workarounds we could try
