### ISSUE TITLE
PersistentVolumeClaim k8s resource generation is not supported as well as volume persistentVolumeClaim in the Pod resource 

### ISSUE THREAD

**Issue by stankevichevg** [lightbend/reactive-cli#149]
At this moment as I can see from the source of PodTemplate.scala it is not possible to claim k8s persistent volume. Generation of the PersistentVolumeClaim resource is not supported too. If I understand reactive-cli responsibility right, it would be useful to support it.

**Comment by TimMoore** [comment]
Lightbend Orchestration is no longer actively developed and will reach its [End of Life](https://developer.lightbend.com/docs/lightbend-platform/2.0/support-terminology/index.html#end-of-life-eol-) on April 15, 2020.

We recommend [Migrating to the Improved Kubernetes Deployment Experience](https://developer.lightbend.com/docs/lightbend-orchestration/current/migration.html).
