### ISSUE TITLE
health check for mesos not working correctly

### ISSUE THREAD

**Issue by alanngai** [lightbend/reactive-cli#162]
this is in reference to a [severity 1 support issue](https://docs.google.com/document/d/10d94Rm2wpDbV8ImgK06LcLF3yPFSxfG2bIk3mX6PkHc/edit?ts=5b478b7c).  In particular:

July 1st @ 8:00AM ET - Konrad determined that Mesos was failing after 5 nodes because of missing the health check. So, he enabled that appropriately and the cluster was considered healthy. 

Because of health check generated by rp-tool was incorrect and failing. Reimplemented health check in Mesos configuration to use manual curl solved the issue and unlocked the cluster scaling;

Notes: 
- we did not know if given version of mesos was supported (or tested) with the rp-tool
- the rp generated check "should" work, yet did not -- testing is needed in real scenarios to see if we actually support a thing or not

**Comment by ktoso** [comment]
it was Mesosphere DC/OS Enterprise Version 1.11.1

**Comment by TimMoore** [comment]
Lightbend Orchestration is no longer actively developed and will reach its [End of Life](https://developer.lightbend.com/docs/lightbend-platform/2.0/support-terminology/index.html#end-of-life-eol-) on April 15, 2020.

We recommend [Migrating to the Improved Kubernetes Deployment Experience](https://developer.lightbend.com/docs/lightbend-orchestration/current/migration.html).
