### ISSUE TITLE
Configure binding endpoint related environment variables

### ISSUE THREAD

**Issue by thomschke** [lightbend/reactive-cli#165]
In service mesh environment (Istio) the ingress traffic is passed through a sidecar-proxy. For this reason all application sockets have to bind to 127.0.0.1 (or 0.0.0.0) and NOT to `status.podIP` (see akka/akka-management#209).

Currently all related environment variables "*_HOST" and "*_BIND_HOST" are using `status.podIP`.

https://github.com/lightbend/reactive-cli/blob/5ecc0215ea3d0ed1dceddb2a7cdc184bfbebcd37/cli/shared/src/main/scala/com/lightbend/rp/reactivecli/runtime/kubernetes/PodTemplate.scala#L145
https://github.com/lightbend/reactive-cli/blob/5ecc0215ea3d0ed1dceddb2a7cdc184bfbebcd37/cli/shared/src/main/scala/com/lightbend/rp/reactivecli/runtime/kubernetes/PodTemplate.scala#L149

**Comment by TimMoore** [comment]
Lightbend Orchestration is no longer actively developed and will reach its [End of Life](https://developer.lightbend.com/docs/lightbend-platform/2.0/support-terminology/index.html#end-of-life-eol-) on April 15, 2020.

We recommend [Migrating to the Improved Kubernetes Deployment Experience](https://developer.lightbend.com/docs/lightbend-orchestration/current/migration.html).
