### ISSUE TITLE
Error: Unknown option --transform-pod-controllers

### ISSUE THREAD

**Issue by bwmills** [lightbend/reactive-cli#174]
Hi Lightbend,

Environment: `GKE`
rp version: `rp (Reactive CLI) 1.3.0`,  `jq support: Available`
jq version: `jq-1.5`

Using `rp` to generate Kubernetes resource files (in this case a StatefulSet manifest). 

All is working well in general - thanks for a great CLI. 

Have a script with a function that runs `rp` with multiple flags to transform (extend) the manifest.

```
function generateServiceManifest() {
  rp generate-kubernetes-resources "$1"  \
    --generate-pod-controllers \ 
    --pod-controller-replicas 2 \
    --pod-controller-image-pull-policy Always \
    --env ... \
    --env ... \
    --external-service "..." \
    --external-service "..." \
    --transform-pod-controllers '.spec.template.spec.nodeSelector[0] = {pool:"svc"}' \
    --transform-pod-controllers '.spec.template.spec.containers[0].resources = {requests:{cpu:"1000m",memory:"3Gi"},limits:{cpu:"1000m",memory:"3Gi"}}'
}
```

Focusing on the `--transform-pod-controllers` flag, in this case I'm just creating a nodeSelector:
```
nodeSelector:
  - pool: svc
```
and some resources for the pod:
```
resources:
  requests:
    cpu: "1000m"
    memory: "3Gi"
  limits:
    cpu: "1000m"
    memory: "3Gi"
```
If I run each `--transform-pod-controllers` individually, all is well (the manifest YAML is updated as desired), however if I attempt both (as shown above) in the function, I get:

```
Error: Unknown option --transform-pod-controllers
```
Is this as designed and I need to adjust my `jq` syntax to include everything within one instance of the flag, or is there a way to specify the same flag again (i.e. for each transform)?

**Comment by ihostage** [comment]
I think the jq `pipe` is useful 😄 We're using it for all transformation that not supported in CLI yet.
```bash
#!/bin/bash
loadJson() {
    echo $(cat ./${1}|tr -d '\r\n\t ')
}

serviceName="{{ service_name }}"
volumes=$(loadJson "volumes.json")
volumeMounts=$(loadJson "volumeMounts.json")
readinessLiveness=$(loadJson "readinessLiveness.json")

transformPodControllers="\
    .spec.template.metadata.labels += {\"date\": \"$(date +%s)\"} | \
    .spec.revisionHistoryLimit = {{ revision_history_limit }} | \
    .spec.template.spec.containers |= map(select(.name == \"${serviceName}\").volumeMounts += ${volumeMounts}) | \
    .spec.template.spec.containers |= map(select(.name == \"${serviceName}\") += ${readinessLiveness}) | \
    .spec.template.spec.volumes += ${volumes} | \
    .spec.template.spec.nodeSelector |= {\"domain.com/role\": \"services\"}
"

rp generate-kubernetes-resources \
    -o deploy.yml \
    --generate-all \
    --registry-disable-https \
    --namespace {{ k8s_namespace }} \
    --deployment-type rolling \
    --pod-controller-replicas {{ replicas }} \
    --pod-controller-image-pull-policy Always \
    --transform-pod-controllers "${transformPodControllers}" \
    --ingress-annotation "nginx.ingress.kubernetes.io/ssl-redirect=false" \
    service:{{ service_version }}

kubectl apply -f deploy.yml
```

**Comment by bwmills** [comment]
Thanks @ihostage - that's quite useful as an example - much appreciated.

**Comment by ihostage** [comment]
By the way, settings for resource limits are supported. Maybe not documented, but supported 😄 
https://github.com/lightbend/sbt-reactive-app/blob/master/src/main/scala/com/lightbend/rp/sbtreactiveapp/SbtReactiveAppKeys.scala

Just add settings for SBT project:
```scala
lazy val `service-impl` = project("service-impl")
  ...
  .settings(memory := 512*1024*1024) // 512m
  .settings(cpu := 1.0)
```

**Comment by bwmills** [comment]
Thanks again @ihostage - that's definitely helpful as well.

**Comment by TimMoore** [comment]
Lightbend Orchestration is no longer actively developed and will reach its [End of Life](https://developer.lightbend.com/docs/lightbend-platform/2.0/support-terminology/index.html#end-of-life-eol-) on April 15, 2020.

We recommend [Migrating to the Improved Kubernetes Deployment Experience](https://developer.lightbend.com/docs/lightbend-orchestration/current/migration.html).
