### ISSUE TITLE
Rename labels to app as opposed to appName

### ISSUE THREAD

**Issue by eed3si9n** [lightbend/reactive-cli#183]
###  steps

Generate YAML.

### problem

```
  labels:
    appName: "bootstrap-dns-demo"
```

### expectation

Akka Management documentation (https://developer.lightbend.com/docs/akka-management/current/bootstrap/kubernetes-api.html) uses `app` as the label name. We should be consistent.

```
  labels:
    app: "bootstrap-dns-demo"
```

This is subtle enough to miss, and could take hours to debug.

**Comment by eed3si9n** [comment]
Or akka.lightbend.com/service-name.

**Comment by TimMoore** [comment]
Relates to akka/akka-management#411

**Comment by eed3si9n** [comment]
@TimMoore I guess it depends on the consensus around the label name.
If we can agree on something this feels like a low hanging fruit.
