### ISSUE TITLE
Update value for Cluster Bootstrap Contact Point Discovery

### ISSUE THREAD

**Issue by chuanyeong** [lightbend/reactive-cli#187]
https://github.com/lightbend/reactive-cli/blob/0ed7c1c75f0aa3f286cd81ed2e1fe2f001be6d56/cli/shared/src/main/scala/com/lightbend/rp/reactivecli/runtime/kubernetes/PodTemplate.scala#L95

Currently sets `akka.management.cluster.bootstrap.contact-point-discovery.discovery-method` to `kubernetes-api`

Which would lead to 
![screen shot 2019-01-17 at 11 16 26 am](https://user-images.githubusercontent.com/40765496/51294185-cf580680-1a4c-11e9-970c-9753e4a56668.png)

Correct configuration should be `akka.discovery.kubernetes-api` according to [Akka Management](https://github.com/akka/akka-management/blob/master/docs/src/main/paradox/bootstrap/kubernetes-api.md)

**Comment by eed3si9n** [comment]
What Lagom, Akka, and sbt-reactive-app version are you using?

Orchestration 1.6.0 was tested using Akka Management 0.20.0.
Its implementation prepends `akka.discovery.` - https://github.com/akka/akka-management/blob/v0.20.0/discovery/src/main/scala/akka/discovery/ServiceDiscovery.scala#L73

**Comment by eed3si9n** [comment]
Note on latest Akka 2.5.19 with https://github.com/akka/akka/pull/25937/commits/9352009f32a6ff42bf45f6f113e93531865fdb4e `akka.discovery.kubernetes-api` might not work.

**Comment by chuanyeong** [comment]
Thanks for the quick response.

We're on Lagom 1.4, so that's Akka 2.5

As for Akka Management, we're on 0.19.0, but according to 

https://github.com/akka/akka-management/blob/v0.19.0/discovery/src/main/scala/akka/discovery/ServiceDiscovery.scala#L70

the configName assignment still works in similar fashion.

Either way, in this case what would be the more future-proof way forward?

**Comment by eed3si9n** [comment]
For now you should align with Orchestration 1.6.0 if you're on Lagom 1.4 - https://developer.lightbend.com/blog/2019-01-09-orchestration-1-6-0/

**Comment by chuanyeong** [comment]
We've made the switch to Orchestration 1.6.0 and that fixed the problem.

Thanks!
