### ISSUE TITLE
cannot use gitlab registry

### ISSUE THREAD

**Issue by Simiil** [lightbend/reactive-cli#188]
i am using gitlab as the docker registry, and `rp` has an issue connecting to it:

`rp generate-kubernetes-resources --registry-username name --registry-password pass .... --generate-all "registry.my_gitlab/my_image"`

returns:

`[error, com.lightbend.rp.reactivecli.Main$] Failed to obtain Docker config for registry.my_gitlab/my_image, -1: no response from https://registry.my_gitlab/v2/my_image/tags/list?n=1`

specifying the image version (e.g. `my_image:1.0-SNAPSHOT`) works, so the basic communication to the registry does work.

i am using `reactive-cli 1.6.0`

**Comment by ihostage** [comment]
Are you sure, that you want to use `rp` without image version? I think that it's a strange case. Do you have a `latest` tag for the image?

**Comment by Simiil** [comment]
after some further debugging this seems to be a networking problem on our side.
