### ISSUE TITLE
`rp … --deployment-type rolling --akka-cluster-join-existing` results in incorrect yaml.

### ISSUE THREAD

**Issue by megri** [lightbend/reactive-cli#193]
Link to discussion: https://gitter.im/lagom/lagom?at=5c52f4c754f21a71a1d68630

`rp generate-kubernetes-resources "myservice:<GIT-COMMIT-HASH>" --generate-pod-controllers --generate-services --pod-controller-replicas 3 --deployment-type rolling --akka-cluster-join-existing` generates yaml that will be rejected by `kubectl apply`:

```
The Deployment "myservice" is invalid: spec.template.metadata.labels: Invalid value: map[string]string{"appNameVersion":"myservice-v<GIT-COMMIT-HASH>"}: `selector` does not match template `labels`
```

Adding a label at `spec.template.metadata.labels.appName = myservice` manually resolves the issue.

**Comment by IntelligyScience** [comment]
The same issue here. Is their a way to fix that?

**Comment by ihostage** [comment]
@IntelligyScience Try using `jq` for adding a label manually.
```
 --transform-pod-controllers ".spec.template.metadata.labels += {\"appName\": \"myservice\"}"
```

**Comment by IntelligyScience** [comment]
Thanks, that works :+1:

**Comment by TimMoore** [comment]
Lightbend Orchestration is no longer actively developed and will reach its [End of Life](https://developer.lightbend.com/docs/lightbend-platform/2.0/support-terminology/index.html#end-of-life-eol-) on April 15, 2020.

We recommend [Migrating to the Improved Kubernetes Deployment Experience](https://developer.lightbend.com/docs/lightbend-orchestration/current/migration.html).
