### ISSUE TITLE
rp still generates port 10000

### ISSUE THREAD

**Issue by Simiil** [lightbend/reactive-cli#205]
After updating to 1.7.1, the connection to the declared api endpoints does not work.

[this blog post](https://www.lightbend.com/blog/released-lightbend-orchestration-171-and-sbt-native-packager-1318) suggests that the ports for the API are now at 9000, and the running container seems to listen on port 9000:

    tcp        0      0 10.11.2.101:2552        0.0.0.0:*               LISTEN      1/java
    tcp        0      0 0.0.0.0:9000            0.0.0.0:*               LISTEN      1/java
    tcp        0      0 10.11.2.101:8558        0.0.0.0:*               LISTEN      1/java

the generated `yaml` however still shows the old 10000 port:

    ports:
    - containerPort: 10000
    name: http
    - containerPort: 2552
    name: remoting
    - containerPort: 8558
    name: management

and for the service too:

    ports:
    - name: http
      port: 10000
      protocol: TCP
      targetPort: 10000
    - name: remoting
      port: 2552
      protocol: TCP
      targetPort: 2552
    - name: management
      port: 8558
      protocol: TCP
      targetPort: 8558

am i doing something wrong?

**Comment by eed3si9n** [comment]
I think it's a bug https://github.com/lightbend/sbt-reactive-app/pull/182
