### ISSUE TITLE
Refactor build pipeline

### ISSUE THREAD

**Issue by longshorej** [lightbend/reactive-cli#21]
`build` and/or `prepare` are pretty big, can they be split up into smaller methods?

**Comment by dwijnand** [comment]
I think this issue spawns from this review comment: https://github.com/lightbend/reactive-cli/pull/17#pullrequestreview-76254854

But was actually resolved within the PR.

So closing. Please re-open if I'm mistaken!

**Comment by longshorej** [comment]
I think there's some useful stuff in this project's build pipeline that could be factored out into a separate project for other Scala native projects to consume. But that would require a larger time investment to generalize it, so makes sense to close this issue for now.

**Comment by dwijnand** [comment]
That makes sense. Thanks Jason!
