### ISSUE TITLE
Bintray Debian GPG keys missing

### ISSUE THREAD

**Issue by longshorej** [lightbend/reactive-cli#43]
This is intermittent and I believe is actually a Bintray bug, but occasionally after making a release the `Release.gpg` files aren't created and `apt` complains.

You can kick off the recalculation at Bintray to fix this. If it continues to be an issue, maybe we'll have to automate this or something..

`curl --user longshorej --data ''  https://bintray.com/api/v1/calc_metadata/lightbend/deb`

**Comment by Myrddin27** [comment]
This is currently affecting fresh installs and updating to the latest version on Ubuntu 16.04 LTS (Xenial)

I receive the following error when running `apt update` on an existing installation: 
```
E: The repository 'https://dl.bintray.com/lightbend/deb xenial Release' is no longer signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

And the following when running the installation instructions found at [Tech Hub / Docs / Lightbend Orchestration / CLI Installation](https://developer.lightbend.com/docs/lightbend-orchestration/current/cli-installation.html#debian-ubuntu)
```
W: The repository 'https://dl.bintray.com/lightbend/deb xenial Release' is not signed.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  libre2-1v5
The following NEW packages will be installed:
  libre2-1v5 reactive-cli
0 upgraded, 2 newly installed, 0 to remove and 294 not upgraded.
Need to get 1,432 kB of archives.
After this operation, 558 kB of additional disk space will be used.
Do you want to continue? [Y/n] Y
WARNING: The following packages cannot be authenticated!
  reactive-cli
Install these packages without verification? [y/N] 
```


If it's as simple as running the recalculation that @longshorej mentioned above, can this be fixed? Adding an additional automation step to the release process that guards against this also seems trivial.

**Comment by longshorej** [comment]
@mitkus @dwijnand IIRC there's a paragraph in bold red font in the release process document on Google Docs that covers the issue @Myrddin27 is reporting.

Basically, after every release Bintray isn't signing the packages and that process needs to be kicked off manually. Alternatively, I've used [aptly](https://www.aptly.info/) to build the Debian repository metadata and host it as a static site.

**Comment by dwijnand** [comment]
I believe @mitkus has solved this now.
