### ISSUE TITLE
Docker Authentication Improvements

### ISSUE THREAD

**Issue by longshorej** [lightbend/reactive-cli#48]
Raised by @dbrinegar in https://github.com/lightbend/reactive-cli/pull/45#pullrequestreview-79618816

> Pragmatically we need something, but there seems much to consider here. Feels not great to make a new credential system on top of existing credential system customer is already managing. I wish we had a docker lib that provided all of this.

It would be nice if we could inspect the credentials docker uses after `docker login`. With the default credential store, this is straight-forward as an OAuth token is simply stored in `~/.docker/config.json`. This gets more complicated when supporting the keychain based stores.

I still think it makes sense to layer support ontop of this to be flexible. So, first check the docker credentials (If docker is installed, it doesn't have to be). If there's a valid token there, great. If not, see if there's credentials declared locally in our own format.

**Comment by longshorej** [comment]
@mitkus Would you like to give this one a shot? When we do a request to a private registry, we check some local files for username/password. I think we can provide a better experience for some users -- in the majority of cases (i.e. not if they configured a keychain for docker) -- by reading `~/.docker/config.json` (if it exists) for an OAuth token for the registry in question.

Basically, I think the logic in `getWithToken` needs to be expanded to first attempt with a local docker-stored OAuth token if one exists, and then if that fails with 401 then fallback to the basic auth `credentials` as it does today.

**Comment by mitkus** [comment]
This got slightly more involved than I expected.

Getting token from config.json is easy enough, but new docker versions by default store credentials in OS-specific enclaves: https://docs.docker.com/engine/reference/commandline/login/#credentials-store

I was integrating mac os keychain commandline utility `security`, though it seems there's an easier way. Docker ships with these helpers: https://github.com/docker/docker-credential-helpers/, they seem to provide access to the passwords using unified interface, regardless where they are stored. Trying it out!
