### ISSUE TITLE
Speed up build

### ISSUE THREAD

**Issue by fsat** [lightbend/reactive-cli#62]
Travis allows caching files by using the `cache` directive.

We can speed up the build time if we perform `docker save` of the images used for packaging CLI distros, ask Travis to cache these saved images using the `cache` directive, and then loading these images using `docker load` before the next build.

When attempting to `docker load`, detecting the presence of image file will be necessary as it's not guaranteed the image will be present (especially for the first time this change is implemented).

**Comment by longshorej** [comment]
In addition, for now, let's just build centos-7 and ubuntu-16-04 for PRs as that should catch most issues. I am comfortable with other issues being caught as part of the release process.
