### ISSUE TITLE
Improve the display of help messages

### ISSUE THREAD

**Issue by longshorej** [lightbend/reactive-cli#77]
Quoting Felix:

> I think the help text can be made to display nicer:
> 
> Commands should have a line break separator.
> Provide example values for CPU, memory, disk, ingress annotations, external service

**Comment by TimMoore** [comment]
Lightbend Orchestration is no longer actively developed and will reach its [End of Life](https://developer.lightbend.com/docs/lightbend-platform/2.0/support-terminology/index.html#end-of-life-eol-) on April 15, 2020.

We recommend [Migrating to the Improved Kubernetes Deployment Experience](https://developer.lightbend.com/docs/lightbend-orchestration/current/migration.html).
