### ISSUE TITLE
Automate macOS/Windows releases

### ISSUE THREAD

**Issue by longshorej** [lightbend/reactive-cli#78]

**Comment by longshorej** [comment]
Closing this; I just don't see it as a problem right now. Windows and macOS releases [are documented](https://docs.google.com/document/d/1PZWRrDM2OojVLyaaFzcAVIi8W9F7BPBrO0Abir7NfBA/edit#heading=h.a33iwiyz55d6) and the steps are quite simple.

**Comment by longshorej** [comment]
Eh, after doing the tar.gz stuff today, this would be minimal work and a decent gain. Low priority.

**Comment by TimMoore** [comment]
Lightbend Orchestration is no longer actively developed and will reach its [End of Life](https://developer.lightbend.com/docs/lightbend-platform/2.0/support-terminology/index.html#end-of-life-eol-) on April 15, 2020.

We recommend [Migrating to the Improved Kubernetes Deployment Experience](https://developer.lightbend.com/docs/lightbend-orchestration/current/migration.html).
