### ISSUE TITLE
kubectl segfault results in output

### ISSUE THREAD

**Issue by longshorej** [lightbend/reactive-cli#84]
Noted by @deanwampler on Slack in #general.

If `kubectl` is segfaulting on a machine, `rp` is showing some of the `system` output. It shouldn't be.

```
deanwampler [4:12 PM] 
Worked for me, but I got this interesting error:


[4:12] 
 ```$ rp version
sh: line 1: 85446 Segmentation fault: 11  'kubectl' 'api-versions' '--request-timeout=1s' > /var/folders/9y/xbv_k3dj5kdd_yldx177g5640000gp/T/reactive-cli-1391668215.temp 2>&1
rp (Reactive CLI) 0.6.0
jq support: Available```


[4:12] 
A `kubctl` issue:


[4:12] 
 ```$ which kubectl
/usr/local/bin/kubectl
$ kubectl --version
[1]    85539 segmentation fault  kubectl --version```
(edited)

```

**Comment by deanwampler** [comment]
I looked into this a bit more and found that the `kubectl` isn't from HomeBrew, even though it was in `/usr/local/bin` and it dated from August 2016. I deleted it, installed using HomeBrew, and now `rp version` works fine.
