### ISSUE TITLE
Implement "Job" specification

### ISSUE THREAD

**Issue by dsugden** [lightbend/reactive-cli#90]
Provide a command to enable the specification of a K8s "Job"

https://kubernetes.io/docs/concepts/workloads/controllers/jobs-run-to-completion/

maybe something like rp generate-kubernetes-job

**Comment by longshorej** [comment]
@dsugden At SLB, are the jobs part of the same docker image as their application? If so, I assume they have a different command then? Just trying to think about how to model this.

**Comment by dsugden** [comment]
Yes, the Jobs have a different main class. So some Apps will have a companion Job (specified with different main class). It will join the cluster, issue some commands into cluster and leave cluster and System.exit()

**Comment by longshorej** [comment]
(FYI - The Low Priority move yesterday was a mistake :wink:)

**Comment by longshorej** [comment]
First PR: https://github.com/lightbend/sbt-reactive-app/pull/71

Two more to come:

* CLI PR to respect com.lightbend.rp.applications and honor a `--application` flag that defaults to `default`
* CLI PR to implement `--pod-controller-type` with types `Job` and `Deployment`, defaults to `Deployment`. This should be case insensitive.

**Comment by longshorej** [comment]
Second PR: https://github.com/lightbend/reactive-cli

Last one to come:

* CLI PR to implement --pod-controller-type with types Job and Deployment, defaults to Deployment. This should be case insensitive.

**Comment by longshorej** [comment]
This is implemented. @dsugden I'll ping you when we've done releases in the next few days. Might bleed into early next week.
